### ISSUE TITLE
The graph panes need to load twice in order to enable their callbacks

### ISSUE THREAD

**Issue by FRYoussef** [Grasia/dao-analyzer#17]
Using Dash as multipage-app breaks the graph panes callback. The first load of each app doesn't register the callback associated with each graph pane; however, it works if you reload the page.

I temporarily fix it loading the state of each app in the `main_view_controller`, before the URL callback is launched.

**Comment by daviddavo** [comment]
Only calling `get_layout` from the *main* thread seems to fix the problem...

I think the singleton pattern and the multithreading may be breaking the app.

The `get_service` function is called from different threads, and I think there is no guarantee for synchronization

Logs (from printf):
```
Calling get_layout from thid 140314151151168
127.0.0.1 - - [20/Sep/2021 11:40:11] "GET /daostack HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2021 11:40:11] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2021 11:40:11] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2021 11:40:11] "GET /assets/favicon.ico?m=1631778193.0073225 HTTP/1.1" 200 -
Calling get_layout from thid 140313892222528
```

**Comment by daviddavo** [comment]
According to the [documentation](https://dash.plotly.com/basic-callbacks), "when the Dash app starts, it automatically calls all of the callbacks with the initial values of the input components in order to populate the initial state of the output components." [[1](https://dash.plotly.com/basic-callbacks)]. The problem is that the `update_chart` callbacks are created when the `ChartController`s are created, which are created on the first `get_layout()` call. If this call is made before the app starts (as `index > main_view_controller.bind_callbacks`), the callbacks will be bound and then called. 

On the contrary, if the first `get_layout` call is made INSIDE another callback, then the callbacks won't be called initially until another page refresh. I think we have the following alternatives:

- Creating a `initialize()` function for the services that should be called in either `main_view_controller.bind_callbacks` or `index.py`
- Somehow make a forceful call to the callback after binding it

Furthermore, I think we should make the Services singletons' more transparent, using a decorator like in [this example](https://stackoverflow.com/questions/6760685/creating-a-singleton-in-python)
